-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: May 04, 2023 at 09:45 AM
-- Server version: 10.4.27-MariaDB
-- PHP Version: 8.2.0

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `cmr_db`
--

-- --------------------------------------------------------

--
-- Table structure for table `account`
--

CREATE TABLE `account` (
  `id` int(11) NOT NULL,
  `name` varchar(255) NOT NULL,
  `username` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL,
  `type` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `account`
--

INSERT INTO `account` (`id`, `name`, `username`, `password`, `type`) VALUES
(1, 'CCSIT', 'ccsit', 'ccsit', 'ADMIN'),
(2, 'Graduate Studies', 'graduatestudies', 'graduatestudies', 'ADMIN');

-- --------------------------------------------------------

--
-- Table structure for table `files`
--

CREATE TABLE `files` (
  `id` int(11) NOT NULL,
  `admin_id` int(11) NOT NULL,
  `author` text NOT NULL,
  `title` text NOT NULL,
  `date_submission` date NOT NULL,
  `adviser` text NOT NULL,
  `abstract` text NOT NULL,
  `keywords` text NOT NULL,
  `file_name` text NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `files`
--

INSERT INTO `files` (`id`, `admin_id`, `author`, `title`, `date_submission`, `adviser`, `abstract`, `keywords`, `file_name`, `created_at`) VALUES
(2, 1, 'Ryan C. Sereno, Dennis P. Sungahid, Jehan G. Coquilla, Je Ann Hilongo, Sara D. Ibanez, Mark Loui Rabe', 'Student and Faculty Clearance Processing System', '2022-12-20', 'Czarina Ancella G. Gabi, PhD', 'The Students and Faculty Clearance Processing System is a web-based automated system that aimed to replace the manual method of processing the clearances of the students and faculty at Talisay National High School. This system can eliminate the challenges encountered by simplifying the process and ensuring the integrity and accuracy of the information by providing every student and faculty member with access to the clearance system. Students and faculty members can view the updates and progress of their clearance using their computers or mobile devices, wherever they are. This process is very efficient and can save a lot of paper. The developed system facilitates a more accessible and convenient way of clearing the students\' and faculty member\'s obligations to the school. Clearance certificates are readily available in the system or through the registered email once the administrator has verified and approved the submitted documents. Evaluation of the developed system shows that, based on the ISO 25010 standard, it is functional, mostly reliable, mostly usable, very efficient, mostly agreeing for maintainability and portability, mostly secure, and mostly compatible. Hence, the adoption of the developed system is recommended.', 'students, faculty, administrator, clearance process, users, web-base, ISO 25010', 'Capstone2manuscript.pdf', '2023-05-04 06:44:23'),
(3, 1, 'John Kyle Remojo, Harold Guibone, Clive Ashley Jo, Marife Clarnoco, Alona Jean Gozon', 'Faculty Deliverbales Monitoring System with Notification Feature', '2022-12-20', 'James Brian Flores, PhD', 'This study aimed to design and create a faculty deliverables monitoring system with a notification feature. The system allows the faculty member to review their criteria and deliverables, such as grades, syllabi, and learning material. During the development of the system, it has undergone specific steps anchored to the System Development Life Cycle (SDLC). The ISO 25010 system evaluation tool was utilized to determine the performance of the system. The evaluation result shows that the system’s functionality, reliability, usability, efficiency, maintainability, portability, security, and compatibility are all functional. The system is recommended to be adopted and utilized by organizations with similar processes and procedures.', 'faculty deliverable, monitoring system, ISO25010, notification system', 'FACULTY-DELIVERBALES-MONITORING-SYSTEM-PDF.docx.pdf', '2023-05-04 06:08:20'),
(5, 1, 'Renz Antonette Vallinas, Reylance Lacerna, Leonielyn Aboy, Ethel Zobel, Rendel Casaña, Jackielou Bucton', 'CCSIT- RIES Profiling and Monitoring System', '2022-12-20', 'Gilbert Siega, MSIT', 'Life without technology is pointless in today\'s generation. It affects the way individuals communicate, learn, and think. And it makes our everyday living more accessible and more convenient. However, the literature suggests that reporting the projects\' progress and data consolidation can be challenging if several projects are undertaken manually and simultaneously; thus, it will take the administrator at least a day searching for complex copy documents or files to retrieve. This study aimed to create automated profiling of all research and extension proposals and projects. It also manages and monitors the progress of every submission and project through an online platform. Thus, CCSIT-RIES Profiling and Monitoring System was developed with the help of Agile Methodology. The result of the overall performance of the system attained through testing and the evaluation reveals a fully functional, very reliable, very usable, very efficient, strongly agree for maintainability and portability, very secure and very compatible system.', 'research innovation and extension services, profiling, monitoring, ISO25010, agile methodology, web-based', 'CAPSTONE-2-RIES-Incognito-Juniors-Manuscript-v3.pdf', '2023-05-04 06:08:22'),
(6, 1, 'May-An Sarausa, Aj Bhert Salan, Francis Jay Miole, Isidro Siervo, Haidee Tacle, James Lor', 'Web- based Laboratory Inventory Management  System Teaching and Learning', '2022-12-20', 'Czarina Ancella G. Gabi, PhD', 'Web-Based Laboratory Inventory Management System for Teaching and Learning is a web-based system designed for the Institute of Arts and Sciences Department at Southern Leyte State University to manage and monitor laboratory equipment using QR code technology, as well as the availability of supplies and materials. The Waterfall Model was used to create the system. The system evaluation results show that the developed system is mostly functional, mostly reliable, mostly usable, mostly efficient, mostly agreeable in terms of maintainability and portability, mostly secure and mostly compatible. As a result, it is recommended that the organization adopt and use the system.', 'laboratory management, inventory, ISO25010, waterfall model, web-based', '59érs Manuscript.pdf', '2023-05-04 06:08:24'),
(8, 1, 'Ablanque, Mercy Balili, Cherry Lyn Basalo, Julius Victor Gaviola, Ana Marie Libres, Jerihme Noveda, Ivan', 'Web- based Profiling and Inventory of Equipment and Supplies Information System for SLSU Main Campus Clinic', '2022-12-20', 'Jorton A. Tagud, MSIT', 'The profiling and inventory of equipment and supply system is developed to simplify the process made currently in the university clinic. This type of system is a web-based system which the user/administrator can use the system not just in their office but also in other places, this system can easily adopt changes through updating stocks by inserting new items, changing the stocks number and generating reports. The system was developed following the waterfall model. The evaluation results shows that the system is mostly functional, mostly reliable, mostly usable, mostly efficient, mostly maintainable, mostly agree for maintainability and portability, mostly secure and mostly compatible. It is therefore recommended that this system be adopted and utilized to organizations with similar process and procedures.', 'Inventory system, Profiling, Web-based, Waterfall model, ISO25010', 'For-hardbound-Checked-by-Basalo-Pt1-1.pdf', '2023-05-04 06:08:26'),
(9, 1, 'Pol, Cherry Ann, Lumandog, Jezza, Gallano, Renan Jesus, Millan, Sarah Grace, Baldoza, Margie', 'Varsity Profiling and Monitoring Information System', '2022-12-20', 'Mr. Gilbert Siega', 'Varsity Profiling and Monitoring Information System aim to develop a web-based profiling and monitoring information system intended for the varsities in the university. This system will create a profiling database of all varsity members for easy tracking of members and provide an online platform for monitoring whether varsity athletes and coaches are responding appropriately and adapting to an imposed training program, rehearsal, sports events, and competition demands. The system will create and manage profiling information of all varsity members in the University for Easy Retrieval of records. Also, it enables transactions the checking of attendance, and monitoring of the status and performance of the varsity student-athlete during rehearsal, training, competition demands, sports events, etc. The system was developed with the following Waterfall Model. Results of system evaluation reveal that the developed system is mostly functional, reliable, usable, efficient, maintainable, maintainability, portability, secure and compatible. It is therefore recommended that VPMIS be adapted and utilized so that there will be a systematic and timely way to monitor the activities of all varsity at Southern Leyte State University.', 'varsity profiling, monitoring, ISO25010, waterfall model, web-based, VPMIS', 'VARSITY PROFILING AND MONITORING INFORMATION SYSTEM.pdf', '2023-05-04 06:08:28'),
(10, 1, 'Helen Saligue Obus, Jodalyn Catoc Fermano, Ma. Elizabeth Singson Perol, Ryan Gono Madrigal, Paul John Falcone', 'Development of A Document Management System', '2022-12-20', 'Czarina Ancella G. Gabi, PhD', 'This study aimed to design, develop, and evaluate a web-based document management system for Sangguniang Bayan in Zone 1 in Sogod, Southern Leyte. The system provided a highly efficient for an organization to guarantee that electronic copies of ordinance documents are available whenever they are required and to assist in improving the regular filing of ordinances. Additionally, it simultaneously organizes, tracks, and stores file documents, using less paper and being a useful technique for tracking file ordinances. It makes it simple for users to upload, search, examine, edit, display, delete, and view the status of an ordinance. Furthermore, it makes it simple for users to search for and view information for the general public. Evaluation of the developed system shows that based on ISO25010 standard reveals that is fully functional, mostly reliable, very usable, and very efficient, mostly agree for maintainability and portability, mostly secure and mostly compatible. It is therefore recommended that development of DMS be adopted and to utilized to organizations with similar course relative to managing of documents.', 'document management, web-based, ISO25010, IPO Model, DMS', 'Manuscript DMS - Copy.pdf', '2023-05-04 06:08:30'),
(11, 1, 'Jale, Marcelino R., Sarco, Alan Jr. D., Cagalanan, Fiemela Kaye G., Mangmang, Devina P., Bayon, Rosalinda E., Gonzaga, Erwin V., Arinas, Gideon D.', 'Machine Learning- Based Book Recommender System With Predictive Resource Usage Analysis', '2022-12-20', 'Jannie Fleur V. Oraño, MCS', 'Machine Learning-Based Book Recommender System with Predictive Resource Usage Analysis is a web-based concept that provides convenient and efficient services that allow library users to search and view the complete bibliographic information and the book\'s table of contents. They can also rate and recommend books based on their preferences.\r\nK Nearest Neighbors (KNN) algorithm was used to find other members closest to the members who want to find book recommendations and rank them. The proponents also used the Use Case Diagrams, Context Diagrams, and Data Flow Diagrams in Levels 1 & 2 to show the system\'s procedures and functions. In this study, Personal Home Page: Hypertext Processor, or PHP, was utilized as the software. The tools used were XAMPP Server, MySQL, JavaScript, and Bootstrap 5. Various fact-finding methods were applied throughout the analysis, design, development, and evaluation phases of the software’s creation. Fact-finding instruments such as interviewing and observation were applied to determine the requirements of the desired application. Questionnaires were used to measure the system\'s efficiency as evaluated by the Panel Evaluation Committee.\r\nResults of the evaluation of the system were based on the ISO 25010 standard, which showed that the criteria for usability, reliability, and portability ranked as the highest, followed by security, maintainability, and criteria for functionality. Lastly, the efficiency and compatibility of the system rank as the lowest.\r\nThe evaluation of the Machine Learning-Based Book Recommender System showed that the developed system achieved its functional requirements. Therefore, the\r\nvi\r\nproponents highly recommend implementing the system in the University Library for effective and efficient evaluating tools. Using Machine Learning-Based Book Recommender System is an excellent solution to the time-consuming and exhausting task of choosing a specific book that fits your field of study. This research and development project will also give the students and faculty convenience in looking for a book based on a particular COURSE SUBJECT, not just the book\'s title.', 'evaluation, machine learning, book, recommend, web- based, KNN, algorithm, iterative model', 'SLSU Book Recommender System - Final Manuscript.pdf', '2023-05-04 06:08:32'),
(12, 1, 'Mary Roselle Cleo G. Pere, Louise Yvonne Paje, Justin Carl Juanico, Aldrin A. Milla, Emmanuel G. Inderio', 'Southern Leyte State University Hotel Reservation Management With Customers\' Comments Classification and Opinion Mining Analysis', '2022-12-20', 'Ms. Jannie Fleur Oraño', 'In this modern era, technological advancement is very evident. Almost everything can be done with a few clicks; booking reservations is one of them. This research will provide the Southern Leyte State University Hotel with a system that can accommodate students, staff, and guests with their reservations without going physically to the hotel anytime they want. This system, which has customer comment classification and opinion mining analysis, aims to gather guests\' feedback for the system\'s improvement. This system can handle the entire task related to information handling without any complexity and with just a few clicks. With this computerized system, it is easy to retrieve older records from the database, manage all the data related to the customer, like their personal and contact information, and store details about customer payment details, room allotment details, and hotel clearance details. The machine learning method recognizes the polarity of the user\'s opinion by utilizing the sentence\'s triple dependency.', 'None', 'SLSU HOTEL-RESERVATION-MANAGEMENT_TeamBinary.pdf', '2023-05-04 06:08:34'),
(21, 1, 'James Wayne Pagodon, Lalaine Jean Apa, Laarni Marie Ponla', 'Computerized Assets System for BARGO (Business and Resource Generation Office)', '2022-12-20', 'Rene Radaza, MSIT', 'The Computerized Assets System is a web-based system that covers all activities, exercises, and exchanges in the Business and Resource Generation Office (BARGO). It allows BARGO to keep track of its assets, lessen the possible errors in searching the detailed asset information, and keep the data secure. The most significant advantage of this system is the effective management of assets by keeping records of the assets and retrieval of information. In this, we gather the information to define the requirements of the new application and look at factors of how BARGO managed their assets. The computerized Assets System is an example of a new technology that facilitates the search for information on each asset. Based on the transaction agreement, assets can be added or removed from the database at any time. Additionally, it simultaneously organizes, tracks, and stores assets documents using less paper and is a helpful technique for tracking assets information. It makes it simple for users to search, edit, delete, and view the status of the client\'s orders. Furthermore, it makes it simple for users to search for and view information on available and purchased assets. The evaluation result shows the mean for criteria portability for 4.3. It is ranked as the highest, followed by 4.1 for usability, 4.06 for security, 4.0 for efficiency, 3.9 for maintainability and reliability, and 3.8 for functionality. Lastly, the system\'s compatibility criteria rank as the lowest mean of 3.7. Furthermore, the overall weighted mean for the criteria of evaluation result was 3.38.', 'asset, effective management of assets, simultaneously, web- based', 'manuscript-print.pdf', '2023-05-04 06:08:35'),
(22, 1, 'Abrea, Julie Ann, Calindao, Ian, Cano, Juvie, Costillas, Jelly Ann, Obra, Jheselle, Rivas, Ronald', 'Documents Management System for SLSU- Knowledge Transfer and Technology Office', '2022-12-20', 'Mr. Keano Nikko L. Sy', 'In the modern world, technology has taken the lead. It makes our lives easier to complete, faster, better, and more fun due to all these revolutions, and it also helps us improve the planet. Technology is advancing faster, more mobile, and more potent than ever. This project aims to create a document management system to track and manage the files of the knowledge transfer and technology office, creating a safe and well-organized database and technological system that can provide efficient and accurate transaction monitoring. The Document Management System for SLSU-KTT Office can perform its function and meet the functionality needed to address the ITS Office\'s problem. The researchers used (SDLC) method and were analyzed using the waterfall model. The results of this system indicate that the documents management system for SLSU- knowledge transfer and technology office was generally well-received evaluation.', 'Management System, ISO 25010 evaluation, web-based application, UM, Patent, Innovator, Copyright, and Industrial Design.', 'Capstone2-Original.pdf', '2023-05-04 06:08:37'),
(23, 1, 'Mary Ann E. Bongabong, Roselyn S. Peralta, Kim Noriele D. Peras, Sean Davis Bicol, John Royce Urgel, Daisyrie G. Cubio', 'Vehicle Reservation Travel Order Management System (VReTOMS)', '2022-12-20', 'Dr. Rhoderick M. Malangsa', 'In this modern era, technological advancement is very evident. Almost everything can be done with a few clicks; reservations is one of them. This research will provide exclusively in the Office of the Vice President for Administration and Finance in Southern Leyte State University- Main Campus with a system that can accommodate employee, drivers, and in- charge personnel anytime they request a travel order. This system, which has a calendar scheduler to let both in- charge personnel and employees to be updated in every travel details. This system can handle the entire task related to information handling without any complexity and with just a few clicks. With this computerized system, it is easy to manage all the data related to the vechicle reservations and travel orders, like their personal and travel information, and store details about vehicles information. Based on the results of the evaluation the proponents\' respondents test the reliable, mostly usable, and efficient. Reservation and travel order management is vital component for efficient delivery of services in an institution. in the care of Southern Leyte State University the current process in vehicle reservation is in manual way, all documents are needed, stored, and monitored using paper and pen transaction aided with calendar. This study was conducted to augment the current purposes of Vehicle Reservation in the Office of Vice President for administration and Finance. The study was able to integrate computerized database, designed an easy- to- use method and user friendly modules. A dashboard was also developed for easy generate of trip tickets of reports. The develop system iaded the management of all data related to the vehicle reservation and travel order.', 'None', 'manuscript.docx', '2023-05-04 06:08:39'),
(26, 1, 'Grant Junlee Linsag, Arvin Buzon, Ruvie Gultia, Lyndie Espere, Sheralyn Gorduiz, Bonna Ann Villasotes', 'Gender and Development Project Monitoring System', '2022-12-20', 'Mr. Gilbert Siega', 'This capstone project developed an automated monitoring system for Gender and Development (GAD) related projects at Southern Leyte State University-Main Campus (SLSU-MC). The gender and development system were web-based, included a database for profiling GAD-related projects, and provided online access for saving, updating, and retrieving data. The project followed the System Development Life Cycle (SDLC) waterfall model, with phases including analysis, design of the software and system, system processes, deployment and testing, and maintenance. The hardware and software specifications were detailed, including a minimum requirement of an Intel core i3-i5 computer with 8GB RAM, 900 GB, and Windows 10, as well as software such as Visual Studio Code, HTML, CSS, PHP, jQuery, MySQL, and phpMyAdmin. The gender and development project monitoring system results have an overall mean of 4.16 combined with functionality, reliability, usability, efficiency, maintainability, portability, security, and compatibility. ', 'Gender and Development (GAD), Monitoring system, Web- based, Evaluation, ISO 25010 Evaluation', 'Manuscript.docx', '2023-05-04 06:08:41'),
(27, 1, 'Jayno Canete, Clinton Villarino, Mark Jemuel Pauyon, Michelle Morales', 'SLSU Planning Office Dasboard', '2022-12-20', 'Jorton A. Tagud, MSIT', '              In order to build Dashboard that will allow the user to make timely and pertinent decisions to enhance the decision process, the research goal is to design a methodology for analyzing a set of data. Today there are large amounts of data that are difficult to understand in spreadsheet or textual reports, so data visualizations have become an easy and fast way to convey the ideas or objectives that you want to achieve with that data. The objective of this research is to propose a dashboard for data visualization. Dashboard are expected to improve decision making by amplifying cognition and capitalizing on human perceptual capabilities. Hence interest in dashboard has increased recently which is also evident from the providers in the organizations. Despite dashboard popularity, little is known about the extent of their effectiveness. In this paper, the researcher conducts a literature review with an aim to identify the needs of the certain organization that might need to consider when implementing dashboards.', 'None', '2nd part A TEAM CAPSTONE FINAL.docx', '2023-05-04 06:08:42'),
(28, 1, 'Marian Fe B. Oraño, Sherwin Ocularis, Clares Mae L. Perioles, Kevin Cris A. Acosta, Jezron D. Pequero', 'Barangay Health and Nutrition Information System', '2021-08-20', 'Mr. James Brian Flores, Ph. D. ', 'The proposed project named Barangay Health and Nutrition Information System (BHNIS) is a web-application that combines barangay health and nutrition information system into a single platform for simple administration and communication. The application was created to provide the barangay health workers and the people/community of Barangay Lewing, Anahawan, Southern Leyte with access to emerging technology to be more effective and efficient in reaching out to people, thus expanding the kingdom.\r\n\r\nThe technology in question makes it simple for barangay health workers to manage the information of the community, such as household profiles, vaccination records, maternal and child health records, and lists of medicines. People in Barangay Lewing, Anahawan, Southern Leyte, on the land, will be able to inquire and make an appointment and they will receive an e-mail for their schedule.\r\n', 'Web Application, Emerging Technology', 'FINALMANUSCRIPT - BHANIS.docx', '2023-05-04 06:08:44'),
(29, 1, 'Oclarit, Danielle A., Olais, Paolo E., Nalimot, Honey Grace C. Nacorda, John Dave E., Polancos, Shenna Mae D.', 'SLSU OJT Timesheet Monitoring and Journal System Using Face Recognition', '2022-05-20', 'Mr. Rhoderick D. Malangsa', 'OJT Monitoring System was evaluated and tested by the end-users and the results showed that the said application is capable of replacing the manual process of recording for it will simplify the process of posting and checking of accomplishment report of the student. The researchers recommended that end-users be given a tutorial to familiarize themselves with the system\'s features, as well as a follow-up study on how to improve and maintain the OJT Monitoring System. It is a comprehensive information system intended to manage, record and track the progress of students in their On-the-Job Training course. The said project will be able to allow the students to post their daily task and accomplishment report on this platform. This will serve as a communication tool for their students as well as a way for them to avoid dishonesty when entering their attendance time since it is not done manually.', 'On the Job Training, OJT Monitoring System, accomplishment reports, communication tool, IT specialists, publishing', 'Team-AdelaMelisent-Manuscript.pdf', '2023-05-04 06:09:28'),
(30, 1, 'Roy Joshua S. Oclarit, Joshua A. Bahinting, Raffy V. Laviña, Mary Dianne B. Alvares, Geraldine Cahigus', 'Rice Plant Disease Detector and Severity Calculator Using Machine Learning and Visual Computing', '2022-05-20', 'Ms. Jannie Fleur V. Oraño', 'None', 'None', 'RPDDSC-Manuscript.pdf', '2023-05-04 06:09:29'),
(31, 1, 'Hontiveros, Jericho James L., Godinez, Arlenie Mae M., Justol, Sheila Mae S., Escano, Roslyn B., Imboc,Joey Mae T.', 'College of Information and Computer Studies Online Information System', '2022-05-20', 'Dr. Geraldine B. Mangmang', 'With the rapid development of technology, a lot of work can be done in the fastest way. Most entrepreneurs invest in computer-based applications to cater to their business needs, especially in their sales and inventories. This study focuses on the development of a computer-based Sales and Inventory Management System with Sales Forecasting using the Python programming language and MySql for the database for Big Boy Agri-vet Supply. The system will enhance the stores\' current method of calculating the customers\' total purchases using a traditional calculator. It will also have a feature that will track the number of remaining stocks in the inventory and have the capability to predict the market sales of a product in a specific period of time.', 'Sales and Inventory System, Sales Forecasting, Machine Learning', 'Manuscript-E-Team.._065132.pdf', '2023-05-04 06:09:31'),
(32, 1, 'Arnaiz, Irene B., Brillo, Cesar D., Fortaliza, Jenny M., Garzon, Medilyn C.', 'TRI-RIDE: A Web- based Tricycle Booking System with GPS and Navigation', '2022-05-20', 'Keano Nikko L. Sy', 'Transportation is one of the most important things that every day has a tremendous development. Transport and communication are considered the cornerstones of many human civilizations because of their importance in linking neighboring barangays and towns to each other. A three-wheeled vehicle known as “tricycle” is one of the most common transports operated in Bato, Leyte.  Some commuters chose their fare to tricycle than busses as primary commodity in going to work, buying foods in town market, etc. However, problem arrive during 2019, 5Coronavirus Disease (2019) pandemic change everything. Coronavirus Disease has been the biggest problem encounter by the tricycle driver. During this time of pandemic, the transportation in the town become limited and the commuters are having trouble when they want to go to other barangays or going into town because of covid-19 protocol. Thus, in this study, a system is designed for the booking of tri-ride trips using GPS technology for navigation and location finding to incorporate the Global Positioning System (GPS). Most people have their own mobile phones, so they can take advantage of the design technology even in remote areas. Furthermore, the main objective of this study is to design and develop a web-based that would act between tricycle drivers and passenger to improving the ride hailing experience.', 'None', 'Appendix D - Project Manuscript Outline.docx', '2023-05-04 06:09:33'),
(33, 1, 'Oclarit, Danielle A., Olais, Paolo E., Nalimot, Honey Grace C., Nacorda, John Dave E., Polancos, Shenna Mae D.', 'SLSU OJT Timesheet Monitoring and Journal System Using Face Recognation', '2022-05-20', 'Mr. Rhoderick D. Malangsa', 'OJT Monitoring System was evaluated and tested by the end-users and the results showed that the said application is capable of replacing the manual process of recording for it will simplify the process of posting and checking of accomplishment report of the student. The researchers recommended that end-users be given a tutorial to familiarize themselves with the system\'s features, as well as a follow-up study on how to improve and maintain the OJT Monitoring System. It is a comprehensive information system intended to manage, record and track the progress of students in their On-the-Job Training course. The said project will be able to allow the students to post their daily task and accomplishment report on this platform. This will serve as a communication tool for their students as well as a way for them to avoid dishonesty when entering their attendance time since it is not done manually.', 'On the Job Training, OJT Monitoring System, accomplishment reports, communication tool, IT specialists, publishing', 'Team-AdelaMelisent-Manuscript.pdf', '2023-05-04 06:09:34'),
(34, 1, 'Omatang, Roxanne I., Torrecampo, Pablito Jr.,P., Espultero, Zidric C., Madora, Jamella O., Tibon, Franzel L.', 'Automated Scheduling for Covid-19 Vaccination in Sogod Southern Leyte', '2021-12-20', 'James Brian Flores, PhD,TM', 'The COVID-19 Pandemic has escalated numerous deaths all over the globe. In the fight against the deadly virus, the Philippine government initiated the COVID-19 Mass Vaccination for the whole country to lessen the victims of the deadly foe. As part of the government’s plan to fight off the pandemic the Local Government Unit of Sogod, Southern Leyte have initiated a Local COVID-19 Mass Vaccination. In the said participation this has also resulted to crowd fluctuation in the vaccination site. In line with dilemma, it would be prudent to have a system that could count the expected number of COVID-19 aspirant on a specific vaccination date, to prevent or mitigate crowd fluctuation in all vaccination sites.  ', 'None', 'Appendix D - Research  Project Manuscript Outline.pdf', '2023-05-04 06:09:36'),
(35, 1, 'Steven P. Gubantes, Alfredo A. Kisteria Jr., Emelie Quiawan, Marlo B. Agoylo, Erich John A. Cadayona', 'E- Guidance Consultation System', '2021-07-20', 'Mr. James Brian Flores', 'None', 'None', 'E-GCA-Manuscript(Tropang_Potchi).pdf', '2023-05-04 06:09:38'),
(36, 1, 'Lourence B. Aure, Jack E. Bihay, Andrey N. Mejares, Marco Eraño P. Pahamotang, Carl John Albert S. Solo', 'Image- based Baybayin to Tagalog Word Translator Using Deep Learning Algorithm', '2021-12-20', 'Ms. Jannie Fleur V. Oraño', 'The Baybayin scripts are the Philippines\' oldest writing system that gave Filipinos their identity during the pre-colonial period. However, Baybayin is no longer in use having been replaced by a universal writing system. As part of the Filipino cultural preservation, the Philippine Congress passed House Bill 1022, the \"National Writing System Act\" in 2018 with the goal of reintroducing Baybayin characters as a writing system in the Philippines. Learning and familiarizing Baybayin is a time-consuming procedure and needs expertise in doing so. Thus, this research intends to develop an alternate approach that makes familiarization easier. This project attempts to construct an optical character recognition model that can categorize Baybayin characters using emerging technologies such as deep learning algorithms, machine learning and computer vision. Using a total of 7,360 training samples, the model was able to attain a testing accuracy of 96.87836 percent. This result shows that the model is accurate enough to categorize Baybayin characters. The generated model is embedded in the classification applications and utilized to translate an image of Baybayin word into Tagalog. In addition, this study used OpenCV2 to extract characters from an image using a thresholding algorithm to separate the available features in an image and be able to get the axis of the segmented characters in the image and crop it as a new image to feed into the model. Having such functionality will make it easier for students, professors or any interested individuals to recognize and interpret Baybayin words or characters and will also help them become more comfortable in using such writing system.', 'deep learning, convolutional neural network, ocr, baybayin, segmentation, opencv2', 'Team Bihay - Manuscript.pdf', '2023-05-04 06:09:40'),
(37, 1, 'Borlaza, Semplicio V., Mamolo, Joe Elysium M., Sanz, Dan Lester C., Clarnoco, Divina S., Nacario, Rhylen G.', 'Southern Leyte Endemic Herbal Plant Identification System', '2021-12-20', 'Ms. Jannie Fleur V. Oraño', 'The study described in this manuscript is consists of a system that will involve image processing techniques to extract relevant features related to a leaf of an herbal plant. Using deep machine learning algorithms to detect and identify herbal plants in Southern Leyte. The system will also locate the plants where they would grow. With the use of QGIS for mapping the location of the herbal plant in Southern Leyte.', 'None', 'Manuscript.docx', '2023-05-04 06:09:42'),
(38, 1, 'Angele Rose Dejesica, Mark RJ Marte, Mark Vincent Casilac, Jay Manguilimotan, Roque Pajuyo', 'Image- based Corn Disease Identifier', '2021-12-20', 'Ms. Jannie Fleur V. Oraño', 'None', 'None', 'IBCDIA-Final_Manuscript.pdf', '2023-05-04 06:21:07'),
(39, 1, 'Cinco, Marie Glaiza C., Rosales, Ma. Rotchelle C., Dueñas, Dinalyn, Calope, Allysa S., Gerodias, Jemuel J.', 'Web- based Barangay Mapping in Barangay Consolascion, Sogod Southern Leyte', '2022-05-18', 'Jorton Tagud', 'In the advent of the current technological trend, where everything can be found using a specified search engine. In each available search engine that can be accessed online offers a distinct service from one another, this study aims to have a search engine where the sole purpose is tracing and locating a person’s residency and outputs the result using digitized map-based platform. \r\nThe development\'s purpose is to create a system that would address the necessity to locate a person\'s present residence as well as demographic data. Because the project will be able to generate the information that matches to a person\'s location, the intended user will not be focused on locating a person\'s residence in such instances. The information on a person will be saved in the system, and the intended user will simply conduct a search, with the project producing the appropriate search result.\r\n', 'None', 'WEB-BASED BRGY. MAPPING IN CONSOLACION SL-REVISE.docx', '2023-05-04 06:17:18'),
(40, 1, 'Pepito Rodel, Janola Clark, Laurea Sonny, Reducto Annie, Gildo Jessa Mae', 'The Development of A Web- based Voting Sytem with Mobile Application', '2022-03-02', 'Mrs. Geraldine Mangmang', 'Southern Leyte State University Online Voting System is a web – based platform that caters the candidates profile and platforms, voters list of interest candidates, and personal ballot. The system can able to send email message notification for voters and candidates. This study aims to analyze, design, develop and implement a user - friendly and interactive web – based and mobile student online voting system in Southern Leyte State University Main Campus. Mixed method approach is used in this study since the researcher want to analyze the SSC goals for the proposed system as well as the researcher wants to explore the candidates – student’s relationship. The possible way to collect the data in this study is mixed structure and unstructured questionnaire.', 'Online Voting, SMS Notification, Email Notification, Web-based Platform, Mobile Application.', 'My-capstone-manuscript-edited.pdf', '2023-05-04 06:17:20'),
(41, 1, 'Jess Christian Retulla, Jobe Paran, Kenn Francis Villas, Fred Matthew Espiel', 'CarAvang: Post and Rent Cars Mobile Application System', '2022-05-20', 'Mr. Rhoderick Malangsa', 'Nowadays, driving a private vehicle is one of the most effective way to help prevent the spread of the coronavirus. When using public transportations, there is a very high risk of making contact with someone who carries the virus. And since not all people have the financial capability of buying their own car, this is where the car rental business come in. They provide a car for rent with a rate for how many days you want to rent a car. This can help people who just want to use a car for a specific purpose, without the need of buying a brand-new car in full. Since our technology has greatly advanced through the years, online transactions have become so widely popular in todays’ generations. And renting a car is no exception. With the proposed application of the researchers, people can now rent cars faster and easier with the use of internet connection and a mobile phone. The main objective of the application is to provide a safer alternative to renting a car. Instead of personally going in person to a car rental business, you can just do all of it at your home, via online.', 'None', 'Final Capstone.docx', '2023-05-04 06:17:21');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `account`
--
ALTER TABLE `account`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `files`
--
ALTER TABLE `files`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `account`
--
ALTER TABLE `account`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;

--
-- AUTO_INCREMENT for table `files`
--
ALTER TABLE `files`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=48;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
